project:
  type: website

website:
  title: "Justine"
  site-url: https://JNS2589.github.io/MyBlog
  navbar:
    background: "#E3655B"
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/JNS2589
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/justineshakespeare/
        aria-label: GitHub

execution:
  freeze: auto

format:
  html:
    mainfont: Helvetica
    linkcolor: "#18A999"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]