project:
  type: website

website:
  title: "Justine's Blog"
  site-url: https://JNS2589.github.io/MyBlog
  navbar:
    background: "#9DC7C8"
    right:
      - text: ""
        href: https://github.com/DACSS
      - text: "Contributors"
        file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS
        aria-label: GitHub

execution:
  freeze: auto

format:
  html:
    mainfont: Helvetica
    linkcolor: "#08415C"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]